### PR TITLE
Allow Diasend files with only CGM data present

### PR DESCRIPTION
**Pull request by skuzzer**
Small change to allow Diasend files that don't have any data on the insulin tab to be uploaded

### CODE REVIEW

**Review by gh-davidr — CHANGES_REQUESTED** [review]
Thanks for this Adam.  This has never been an issue from exports I've made.

Would a better change be to insist that either BG, Insulin OR CGM data hss to be present as one tab?

**Comment by skuzzer** [comment]
Good point, that may cover even more use cases which I wasn't thinking of. In my use case I can't upload pump data to Diasend, but I can upload CGM data, so I have a blank Insulin tab.

**Review by gh-davidr — APPROVED** [review]

**Comment by gh-davidr** [comment]
Cool - I'll change it to be more generalized in my local copy and will check in for V3.02 or next increment.

The other work I was tackling (but not started) is to reuse the autotune editor so it can maintain the the same profile data in NS.  I need some guidance on this from submitter as it's not clear how best to handle the dates involved.

**Comment by skuzzer** [comment]
I've updated this so that if any tab has data it will be accepted, hope that's what you meant?

**Comment by skuzzer** [comment]
Closing, this was merged externally

**Pull request closed without merging**
